version: "3.8"

services:
  # Application Service (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atm-cross-currency-prod
    environment:
      - NODE_ENV=development
      - PORT=55099
      - BASE_URL_SERVICE=http://your-domain.com
      # Database Config
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      # ODS Database
      - ODS_DB_HOST=${ODS_DB_HOST}
      - ODS_DB_PORT=${ODS_DB_PORT}
      - ODS_DB_USER=${ODS_DB_USER}
      - ODS_DB_PASS=${ODS_DB_PASS}
      - ODS_DB_NAME=${ODS_DB_NAME}
      # Internal Database
      - S_DB_HOST=${S_DB_HOST}
      - S_DB_PORT=${S_DB_PORT}
      - S_DB_USER=${S_DB_USER}
      - S_DB_PASS=${S_DB_PASS}
      - S_DB_NAME=${S_DB_NAME}
      - S_UPI_NAME=${S_UPI_NAME}
      # RabbitMQ
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      # External API
      - ATM_CLIENT_URL=${ATM_CLIENT_URL}
      # Slack Config
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_ID=${SLACK_ID}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - SLACL_SIGING_SECRET=${SLACL_SIGING_SECRET}
      - SLACK_VERIFY_TOKEN=${SLACK_VERIFY_TOKEN}
      - SLACK_BOT_AUTH_TOKEN=${SLACK_BOT_AUTH_TOKEN}
      - ATM_CROSS_CURRENCY_WEBHOOK_URL=${ATM_CROSS_CURRENCY_WEBHOOK_URL}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:55099/Service?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
#  nginx:
#    image: nginx:alpine
#    container_name: nginx-reverse-proxy
#    ports:
#      - "8001:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx/ssl:/etc/nginx/ssl:ro
#      - nginx-logs:/var/log/nginx
#    depends_on:
#      - app
#    restart: unless-stopped
#    networks:
#      - app-network
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"

networks:
  app-network:
    driver: bridge

#volumes:
#  nginx-logs:
#    driver: local