services:
  atm-cross-currency-node1:
    container_name: atm-cross-currency-node1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=55099
      - NODE_ENV=development
    restart: always
    networks:
      - app-network

  atm-cross-currency-node2:
    container_name: atm-cross-currency-node2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=55099
      - NODE_ENV=development
    restart: always
    networks:
      - app-network

  node-app-prod-1:
    container_name: node-app-prod-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=55099
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

#  node-app-prod-2:
#    container_name: node-app-prod-2
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - PORT=55099
#      - NODE_ENV=production
#    restart: always
#    networks:
#      - app-network
#
  nginx-atm-cross-currency-uat:
    image: nginx:alpine
    container_name: nginx-atm-cross-currency-uat
    ports:
      - "8001:80" # UAT port
    volumes:
      - ./nginx/uat.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - atm-cross-currency-node1
      - atm-cross-currency-node2
    networks:
      - app-network

#  nginx-prod:
#    image: nginx:alpine
#    container_name: nginx-prod
#    ports:
#      - "8002:80" # Production port
#    volumes:
#      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - node-app-prod-1
#      - node-app-prod-2
#    networks:
#      - app-network


networks:
  app-network:
    driver: bridge
# volumes:
#   zookeeper-data:
#   zookeeper-logs:
#   kafka-data:
